# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  port:
    type: int
    default: 8082
    description: HTTP port
  dashboard-configmap:
    type: string
    default: centraldashboard-config
    description: Kubeflow Profile to create
  registration-flow:
    type: boolean
    default: true
    description: Whether to enable the registration flow on sign-in
