# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  additional-menu-links:
    type: string
    default: ""
    description: >
      YAML or JSON formatted string that is a list of Kubeflow Dashboard sidebar items that will be added to the 
      dashboards left hand sidebar.  Each entry should be formatted like: 
      {text: <string>, link: <string>, type: item, icon: <string>}.  For example: 
      '[{text: Another runs, link: /runs, type: item, icon: assessment}]'.
      This is typically easiest to configure from a file - define a YAML or JSON file, then pass to Juju via
      `juju config kubeflow-dashboard additional-menu-links=@myfile.yaml`.
      See [upstream docs](https://www.kubeflow.org/docs/components/central-dash/customizing-menu/) for more details on
      the menu and link format.
  dashboard-configmap:
    type: string
    default: centraldashboard-config
    description: Name of the Kubeflow Dashboard configmap to be created
  port:
    type: int
    default: 8082
    description: HTTP port
  registration-flow:
    type: boolean
    default: true
    description: Whether to enable the registration flow on sign-in
  menu-link-order:
    type: string
    default: '["Notebooks", "Experiments (AutoML)", "Experiments (KFP)", "Pipelines", "Runs", "Recurring Runs", "Volumes", "Tensorboards"]'
    description: > 
      YAML or JSON list of strings defining the order of the links in the dashboard sidebar.  The format is:
      '["text of first link", "text of second link", "text of third link", ...]'.  See README.md for usage instructions.
